services:
  vps2_core:
    container_name: openclaw-13.2-core
    image: openclaw/13.2/core
    restart: always
    build:
      dockerfile: ./Docker/Dockerfile
      context: .
    working_dir: /Application
    volumes:
      - .:/Application
    tmpfs:
      - /tmp/raxon/org
    command: ['/usr/bin/init']
    ports:
      - "5002:80"
      - "5003:443"
    networks:
      - raxon-org-network
networks:
  raxon-org-network:
    driver: bridge
