services:
  vps2_core:
    container_name: docker-13.2-core
    image: docker/13.2/core
    restart: always
    build:
      dockerfile: ./Docker/Dockerfile
      context: .
    working_dir: /Application
    volumes:
      - .:/Application
    tmpfs:
      - /tmp/raxon/org
    command: ['/usr/bin/init']
    ports:
      - "5005:80"
      - "5006:443"
      - "18789:18789"
    networks:
      - raxon-org-network
networks:
  raxon-org-network:
    driver: bridge
